from enum import Enum

class Intent(str, Enum):
    CONTEXT_RETRIEVAL = "CONTEXT_RETRIEVAL"
    QUIZ_GENERATION = "QUIZ_GENERATION"
    EXPLAIN_QUIZ_QUESTION = "EXPLAIN_QUIZ_QUESTION"
    TIMESTAMP_QUERY = "TIMESTAMP_QUERY"
    SUMMARIZE_VIDEO = "SUMMARIZE_VIDEO"
    EXAMPLE_REQUEST = "EXAMPLE_REQUEST"
    NOTES="NOTES"
    FALLBACK = "FALLBACK"

